In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
# device specification
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [5]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [12]:
X = torch.rand(1,28,28)
logits = model(X)

print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
print(pred_probab)
y_pred = pred_probab.argmax(1)
print(y_pred)

tensor([[-0.0277,  0.0102, -0.0171, -0.0255, -0.1010,  0.0061,  0.0330, -0.0397,
          0.0706,  0.0503]], grad_fn=<AddmmBackward0>)
tensor([[0.0976, 0.1013, 0.0986, 0.0978, 0.0907, 0.1009, 0.1037, 0.0964, 0.1076,
         0.1055]], grad_fn=<SoftmaxBackward0>)
tensor([8])
