In [1]:
import torch
import numpy as np

In [3]:
# tensor are very similar to numpy narray, except tensors can run on GPUs or other hardware acceleration

data = [
    [1, 2],
    [3, 4]
]

x_data = torch.tensor(data)
print(x_data)
x_data.dtype

tensor([[1, 2],
        [3, 4]])


torch.int64

In [7]:
# from numpy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)


print(x_np)
x_np.dtype

tensor([[1, 2],
        [3, 4]])


torch.int64

In [13]:
# override the tensor with 1
x_ones = torch.ones_like( x_data)
print(x_ones)

x_zeros = torch.zeros_like(x_data)
print(x_zeros)

x_random = torch.rand_like(x_data, dtype = torch.float)
print(x_random)

tensor([[1, 1],
        [1, 1]])
tensor([[0, 0],
        [0, 0]])
tensor([[0.3691, 0.2444],
        [0.1404, 0.0532]])


In [14]:
# using shape

shape = (2,3,)

rand_tensor = torch.rand(shape)
print(rand_tensor)

one_tensor = torch.ones(shape)
print(one_tensor)

zero_tensor = torch.zeros(shape)
print(zero_tensor)

tensor([[0.4049, 0.2791, 0.3077],
        [0.4032, 0.8889, 0.6014]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
# attribute in a tensor
tensor = torch.rand((3,4))
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)


tensor([[0.0387, 0.9123, 0.5781, 0.9574],
        [0.1085, 0.8695, 0.3543, 0.6528],
        [0.0692, 0.8443, 0.0174, 0.7190]])
torch.Size([3, 4])
torch.float32
cpu
